### ISSUE TITLE
Error: "Could not start '.'" on OS X

### ISSUE THREAD

**Issue by ihatetoregister** [parallaxinc/PropellerIDE#32] opened 2016-02-03 20:15 UTC
I get an error message when I try to build/write to the propeller chip on OS X. I had to move the "Content" folder from within the app to another location and point the links to the new location to get it working. I'm guessing this has to do with permissions to work inside the app folder.

OS: OS X El Cap 10.11.3
PropellerIDE: 0.35.1

**Comment by bweir** [comment] 2016-02-03 21:10
Hi there,

I think I know what the problem is. Let me ask you. Did you upgrade to a
new version from an old version recently? I changed the names of a number
of configuration keys recently as part of some other development, so after
installing the new version, it may look like you have paths for the
compiler but other parts of the IDE can't find the values.

I am assuming that's what happened, but there's an easy way to test. Try
reinstalling PropellerIDE to the regular location again, then in
Preferences, hit the Restore Defaults button.

If that was the problem, you should be able to compile again after that.

Let me know if that does the trick.

**Comment by ihatetoregister** [comment] 2016-02-04 20:57
It did! That was actually the out of the box behavior because it was the first time I run the PropellerIDE. Anyhow, It's working now! Thank you!

**Comment by bweir** [comment] 2016-02-04 22:26
Ah that's quite strange. You're not the only person to report that it did
that. I suspect it's just never writing an initial value on first run. I'll
have to have a look at it. I'm glad you're up and running though!

**Comment by Gadgetoid** [comment] 2016-02-27 13:20
I'd like to chime in and say that I've now also seen this problem on a freshly installed Raspberry Pi, running version 0.36.7. I haven't had any previous installations on this OS. I fixed it by opening up the Preferences dialog and saving.

A possibly related note; Propeller IDE will only let me open a menu *once* after which they don't open again. It also wont let me click on icons apparently at random until I restart the IDE.

**Comment by bweir** [comment] 2016-02-28 02:12
Yeah, I'm failing to write the config file the first time over. Haven't
fixed it yet.

When you say menu, what are we talking about? Context menu? File menu?
Preferences dialog?

What version of Qt does the RPi have?

On Sat, Feb 27, 2016 at 5:20 AM, Philip Howard <notifications@github.com>
wrote:

> I'd like to chime in and say that I've now also seen this problem on a
> freshly installed Raspberry Pi, running version 0.36.7. I haven't had any
> previous installations on this OS. I fixed it by opening up the Preferences
> dialog and saving.
>
> A possibly related note; Propeller IDE will only let me open a menu *once*
> after which they don't open again. It also wont let me click on icons
> apparently at random until I restart the IDE.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/parallaxinc/PropellerIDE/issues/32#issuecomment-189637377>
> .
>



-- 
*Brett Weir*, Founder


Engineering Made Awesome
310.245.1775  • brett@lamestation.com • lamestation.com

**Comment by bweir** [comment] 2016-04-07 12:15
Hey, this should be fixed on the latest version of the IDE: [0.37.0](https://github.com/parallaxinc/PropellerIDE/releases/tag/0.37.0). I'll reopen if its not.

**Closed by bweir** 2016-04-07 12:15 UTC
